dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from users import users_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("dashboard/", include("vora.urls", namespace="vora")),
    path("", include("frontend.urls")),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            form_class=EmailValidationOnForgotPassword
        ),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path("password/", users_views.change_password, name="change_password"),

    path("ckeditor/", include("ckeditor_uploader.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "Sakacom Dashboard"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Dashboard"

vora/urls.py
from django.urls import path
from vora import vora_views
from users import users_views
from frontend import frontend_views

app_name = "vora"
urlpatterns = [
    path("users/", users_views.users, name="users"),
    path("user-details/<int:id>/", users_views.user_details, name="user-details"),
    path("add-user/", users_views.add_user, name="add-user"),
    path("edit-user/<int:id>/", users_views.edit_user, name="edit-user"),
    path("delete-user/<int:id>/", users_views.delete_user, name="delete-user"),
    path(
        "delete-multiple-user/",
        users_views.delete_multiple_user,
        name="delete-multiple-user",
    ),
    path("login/", users_views.login_user, name="login"),
    path("logout/", users_views.logout_user, name="logout"),
    path("groups/", users_views.groups_list, name="groups"),
    path("group-edit/<int:id>/", users_views.group_edit, name="group-edit"),
    path("group-delete/<int:id>/", users_views.group_delete, name="group-delete"),
    path("group-add/", users_views.group_add, name="group-add"),
    path("permissions/", users_views.permissions, name="permissions"),
    path(
        "edit-permissions/<int:id>/",
        users_views.edit_permissions,
        name="edit-permissions",
    ),
    path(
        "delete-permissions/<int:id>/",
        users_views.delete_permissions,
        name="delete-permissions",
    ),
    path(
        "assign-permissions-to-user/<int:id>/",
        users_views.assign_permissions_to_user,
        name="assign-permissions-to-user",
    ),
    path("signup/", users_views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", users_views.activate, name="activate"),
    path("", vora_views.index, name="index"),
    path("index/", vora_views.index, name="index"),
    path("index_2/", vora_views.index_2, name="index_2"),
    path("projects/", vora_views.projects, name="projects"),
    path("contacts/", vora_views.contacts, name="contacts"),
    path("kanban/", vora_views.kanban, name="kanban"),
    path("calendar/", vora_views.calendar, name="calendar"),
    path("messages/", vora_views.messages, name="messages"),
    path("app-profile/", vora_views.app_profile, name="app-profile"),
    path("post-details/", vora_views.post_details, name="post-details"),
    path("email-compose/", vora_views.email_compose, name="email-compose"),
    path("email-inbox/", vora_views.email_inbox, name="email-inbox"),
    path("email-read/", vora_views.email_read, name="email-read"),
    path("app-calender/", vora_views.app_calender, name="app-calender"),
    path("ecom-product-grid/", vora_views.ecom_product_grid, name="ecom-product-grid"),
    path("ecom-product-list/", vora_views.ecom_product_list, name="ecom-product-list"),
    path(
        "ecom-product-detail/",
        vora_views.ecom_product_detail,
        name="ecom-product-detail",
    ),
    path(
        "ecom-product-order/", vora_views.ecom_product_order, name="ecom-product-order"
    ),
    path("ecom-checkout/", vora_views.ecom_checkout, name="ecom-checkout"),
    path("ecom-invoice/", vora_views.ecom_invoice, name="ecom-invoice"),
    path("ecom-customers/", vora_views.ecom_customers, name="ecom-customers"),
    path("chart-flot/", vora_views.chart_flot, name="chart-flot"),
    path("chart-morris/", vora_views.chart_morris, name="chart-morris"),
    path("chart-chartjs/", vora_views.chart_chartjs, name="chart-chartjs"),
    path("chart-chartist/", vora_views.chart_chartist, name="chart-chartist"),
    path("chart-sparkline/", vora_views.chart_sparkline, name="chart-sparkline"),
    path("chart-peity/", vora_views.chart_peity, name="chart-peity"),
    path("ui-accordion/", vora_views.ui_accordion, name="ui-accordion"),
    path("ui-alert/", vora_views.ui_alert, name="ui-alert"),
    path("ui-badge/", vora_views.ui_badge, name="ui-badge"),
    path("ui-button/", vora_views.ui_button, name="ui-button"),
    path("ui-modal/", vora_views.ui_modal, name="ui-modal"),
    path("ui-button-group/", vora_views.ui_button_group, name="ui-button-group"),
    path("ui-list-group/", vora_views.ui_list_group, name="ui-list-group"),
    path("ui-media-object/", vora_views.ui_media_object, name="ui-media-object"),
    path("ui-card/", vora_views.ui_card, name="ui-card"),
    path("ui-carousel/", vora_views.ui_carousel, name="ui-carousel"),
    path("ui-dropdown/", vora_views.ui_dropdown, name="ui-dropdown"),
    path("ui-popover/", vora_views.ui_popover, name="ui-popover"),
    path("ui-progressbar/", vora_views.ui_progressbar, name="ui-progressbar"),
    path("ui-tab/", vora_views.ui_tab, name="ui-tab"),
    path("ui-typography/", vora_views.ui_typography, name="ui-typography"),
    path("ui-pagination/", vora_views.ui_pagination, name="ui-pagination"),
    path("ui-grid/", vora_views.ui_grid, name="ui-grid"),
    path("uc-select2/", vora_views.uc_select2, name="uc-select2"),
    path("uc-nestable/", vora_views.uc_nestable, name="uc-nestable"),
    path("uc-noui-slider/", vora_views.uc_noui_slider, name="uc-noui-slider"),
    path("uc-sweetalert/", vora_views.uc_sweetalert, name="uc-sweetalert"),
    path("uc-toastr/", vora_views.uc_toastr, name="uc-toastr"),
    path("map-jqvmap/", vora_views.map_jqvmap, name="map-jqvmap"),
    path("uc-lightgallery/", vora_views.uc_lightgallery, name="uc-lightgallery"),
    path("uc-lightgallery/", vora_views.uc_lightgallery, name="uc-lightgallery"),
    path("widget-basic/", vora_views.widget_basic, name="widget-basic"),
    path("form-element/", vora_views.form_element, name="form-element"),
    path("form-wizard/", vora_views.form_wizard, name="form-wizard"),
    path(
        "form-editor-ckeditor/",
        vora_views.form_editor_ckeditor,
        name="form-editor-ckeditor",
    ),
    path("form-pickers/", vora_views.form_pickers, name="form-pickers"),
    path("form-validation/", vora_views.form_validation, name="form-validation"),
    path(
        "table-bootstrap-basic/",
        vora_views.table_bootstrap_basic,
        name="table-bootstrap-basic",
    ),
    path(
        "table-datatable-basic/",
        vora_views.table_datatable_basic,
        name="table-datatable-basic",
    ),
    path("page-lock-screen/", vora_views.page_lock_screen, name="page-lock-screen"),
    path("page-error-400/", vora_views.page_error_400, name="page-error-400"),
    path("page-error-403/", vora_views.page_error_403, name="page-error-403"),
    path("page-error-404/", vora_views.page_error_404, name="page-error-404"),
    path("page-error-500/", vora_views.page_error_500, name="page-error-500"),
    path("page-error-503/", vora_views.page_error_503, name="page-error-503"),
    # Slider
    path("slider-view/", frontend_views.slider_view, name="slider_view"),
    path("add-slider/", frontend_views.add_slider, name="add_slider"),
    path(
        "edit-slider/<int:slider_id>/", frontend_views.edit_slider, name="edit_slider"
    ),
    path(
        "delete_slider/<int:slider_id>/",
        frontend_views.delete_slider,
        name="delete_slider",
    ),
    # Events
    path("view-event/", frontend_views.event_view, name="event_view"),
    path("add-event/", frontend_views.add_event, name="add_event"),
    path("event/<int:event_id>/edit/", frontend_views.edit_event, name="edit_event"),
    path(
        "event/<int:event_id>/delete/", frontend_views.delete_event, name="delete_event"
    ),
    # About Page
    path("view-about/", frontend_views.about_view, name="about_view"),
    path("add-about/", frontend_views.add_about, name="add_about"),
    path("about/<int:about_id>/edit/", frontend_views.edit_about, name="edit_about"),
    path(
        "about/<int:about_id>/delete/", frontend_views.delete_about, name="delete_about"
    ),
    # Award
    path("view-award/", frontend_views.award_view, name="award_view"),
    path("add-award/", frontend_views.add_award, name="add_award"),
    path("award/<int:award_id>/edit/", frontend_views.edit_award, name="edit_award"),
    path(
        "award/<int:award_id>/delete/", frontend_views.delete_award, name="delete_award"
    ),
    # ============================Skill ==========================
    path("view-skill/", frontend_views.skill_view, name="skill_view"),
    path("add-skill/", frontend_views.add_skill, name="add_skill"),
    path("skill/<int:skill_id>/edit/", frontend_views.edit_skill, name="edit_skill"),
    path(
        "skill/<int:skill_id>/delete/", frontend_views.delete_skill, name="delete_skill"
    ),
    # ============================ Curriculum ==========================
    path("view-curriculum/", frontend_views.curriculum_view, name="curriculum_view"),
    path("add-curriculum/", frontend_views.add_curriculum, name="add_curriculum"),
    path(
        "curriculum/<int:curriculum_id>/edit/",
        frontend_views.edit_curriculum,
        name="edit_curriculum",
    ),
    path(
        "curriculum/<int:curriculum_id>/delete/",
        frontend_views.delete_curriculum,
        name="delete_curriculum",
    ),
    #   ====================== Course Category ===============
    path(
        "view-course-program/",
        frontend_views.course_program_view,
        name="course_program_view",
    ),
    path(
        "add-course-program/",
        frontend_views.add_course_program,
        name="add_course_program",
    ),
    path(
        "course-program/<int:course_program_id>/edit/",
        frontend_views.edit_course_program,
        name="edit_course_program",
    ),
    path(
        "course-program/<int:course_program_id>/delete/",
        frontend_views.delete_course_program,
        name="delete_course_program",
    ),
    #   ====================== Courses ===============
    path("view-course/", frontend_views.course_view, name="course_view"),

users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from django.core.validators import RegexValidator
from django.contrib.auth.models import Group


class CustomAccountManager(BaseUserManager):

    def create_superuser(self, email, first_name, last_name, password, **other_fields):
        other_fields.setdefault("is_staff", True)
        other_fields.setdefault("is_superuser", True)
        other_fields.setdefault("is_active", True)

        if other_fields.get("is_staff") is not True:
            raise ValueError("Superuser must be assigned to is_staff=True.")
        if other_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must be assigned to is_superuser=True.")

        super_user = self.create_user(
            email, first_name, last_name, password, **other_fields
        )

        return super_user

    def create_user(self, email, first_name, last_name, password, **other_fields):
        # email validation
        if not email:
            raise ValueError(_("You must provide an email address"))

        email = self.normalize_email(email)
        user = self.model(
            email=email, first_name=first_name, last_name=last_name, **other_fields
        )
        user.set_password(password)
        user.save()
        return user


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return f"{instance.email}/{filename}"


# This is the new custom user model
class CustomUser(AbstractBaseUser, PermissionsMixin):
    is_instructor = models.BooleanField(default=False)

    GENDER_CHOICES = (
        ("", "Choose gender"),
        ("Male", "Male"),
        ("Female", "Female"),
        ("Others", "Others"),
    )

    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    gender = models.CharField(max_length=100, choices=GENDER_CHOICES, blank=True)
    avatar = models.ImageField(
        upload_to=user_directory_path, default="profile/image/default.gif"
    )
    dob = models.CharField(
        max_length=150, blank=True, null=True, help_text="Pattern = dd-mm-yyyy"
    )
    phone_regex = RegexValidator(
        regex=r"^\+?1?\d{9,15}$",
        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
    )
    phone_number = models.CharField(
        validators=[phone_regex], max_length=17, blank=True
    )  # Validators should be a list
    groups = models.ManyToManyField(Group, blank=True)
    about = models.TextField(_("about"), max_length=500, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)  # this false work on ui not in admin
    # when user is created, than system send a email after varify  user is active

    objects = CustomAccountManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

templates/vora/pages/courses/add_course.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

    <style>
        .ckeditor {
            width: 100% !important
        }
    </style>

{% endblock %}

{% block message %}
{% include 'vora/elements/alert.html' %}
{% endblock %}

{% block content %}
<form  method="post" enctype="multipart/form-data" novalidate autocomplete="off">
    {% csrf_token %}
    <div class="row items-align-center justify-content-center">
        <div class="col-xl-9 col-lg-9">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Add Course</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form>

                            <div class="form-row">
                                <div class=" col-md-12">
                                    <div class="form-group">

                                        {{ form.media }}
                                        {{ form.as_p }}

                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Add</button>
                        </form>
                </div>
            </div>
        </div>
    </div>	
 </form>
 
 
 
 {% endblock %}
 
 
 {% block additional_js %}
 
 
 
 
 <script>
    function readURL(input) {
 
       if (input.files && input.files[0]) {
             var reader = new FileReader();
             reader.onload = function(e) {
                $('#imagePreview').css('background-image', 'url('+e.target.result +')');
                $('#imagePreview').hide();
                $('#imagePreview').fadeIn(650);
             }
             reader.readAsDataURL(input.files[0]);
       }
    }
    $("#id_avatar").change(function() {
       readURL(this);
    });
 </script> 
 
 
 <script>
    $(".multi-select").select2({
       placeholder: "Select the Role"
   });
 </script>
 
 
 {% endblock %}

templates/vora/pages/courses/add_course_rating.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

    <style>
        .ckeditor {
            width: 100% !important
        }
    </style>

{% endblock %}

{% block message %}
{% include 'vora/elements/alert.html' %}
{% endblock %}

{% block content %}
<form  method="post" enctype="multipart/form-data" novalidate autocomplete="off">
    {% csrf_token %}
    <div class="row items-align-center justify-content-center">
        <div class="col-xl-9 col-lg-9">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Rate Course</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form>

                            <div class="form-row">
                                <div class=" col-md-12">
                                    <div class="form-group">

                                        {{ form.media }}
                                        {{ form.as_p }}

                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Add</button>
                        </form>
                </div>
            </div>
        </div>
    </div>	
 </form>
 
 
 
 {% endblock %}
 
 
 {% block additional_js %}
 
 
 
 
 <script>
    function readURL(input) {
 
       if (input.files && input.files[0]) {
             var reader = new FileReader();
             reader.onload = function(e) {
                $('#imagePreview').css('background-image', 'url('+e.target.result +')');
                $('#imagePreview').hide();
                $('#imagePreview').fadeIn(650);
             }
             reader.readAsDataURL(input.files[0]);
       }
    }
    $("#id_avatar").change(function() {
       readURL(this);
    });
 </script> 
 
 
 <script>
    $(".multi-select").select2({
       placeholder: "Select the Role"
   });
 </script>
 
 
 {% endblock %}

templates/vora/pages/courses/course_view.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static %}

<!-- Additional Css -->
{% block additional_css  %}
<link rel="stylesheet" href="/static/vora/vendor/bootstrap-select/dist/css/bootstrap-select.min.css">
<link rel="stylesheet" href="/static/vora/vendor/datatables/css/jquery.dataTables.min.css" >
{% endblock %}

{% block message %}
{% include 'vora/elements/alert.html' %}
{% endblock %}

{% block content %}

<div class="page-titles">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="javascript:void(0)">Table</a></li>
        <li class="breadcrumb-item active"><a href="javascript:void(0)">Datatable</a></li>
    </ol>
</div>
<!-- row -->


<div class="row">

    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Courses</h4>
                <div class="d-flex">

                    {% if perms.users.add_customuser %}
                    <a href="{% url 'vora:add_course' %}" class="btn btn-primary btn-sm ">ADD COURSE  <span class="btn-icon-end">
                        <i class="fa fa-plus"></i></span>
                    </a>
                    {% endif %}

                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="example3" class="display min-w850">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Program</th>
                                <th>Price</th>
                                <th>Description</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for course in course_data %}
                            <tr>
                                <td>{{ course.id }}</td>
                                <td>{{ course.course_name }}</td>
                                <td>{{ course.program }}</td>
                                <td>{{ course.price }}</td>
                                <td>{{ course.description|truncatewords:5|slice:":150"|safe }}</td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{% url 'vora:update_course' slug=course.slug %}" class="btn btn-primary shadow btn-xs sharp me-1"><i class="fa fa-pencil"></i></a>
                                        <a href="{% url 'vora:delete_course' course.slug %}" class="btn btn-danger shadow btn-xs sharp"><i class="fa fa-trash"></i></a>
                                    </div>												
                                </td>												
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    
</div>

{% endblock %}

{% block additional_js  %}
<script src="/static/vora/vendor/apexchart/apexchart.js"></script>
    
<script src="/static/vora/vendor/datatables/js/jquery.dataTables.min.js"></script>

<script src="/static/vora/js/plugins-init/datatables.init.js"></script>
{% endblock %}

templates/vora/pages/courses/delete_view.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

    <style>
        .ckeditor {
            width: 100% !important
        }
        h2, p, form {
            padding: 10px;
        }
    </style>

{% endblock %}

{% block content %}

  
<div class="container">
    <div class="row items-align-center text-align-center justify-content-center">
        <div class="col-xl-6 col-xxl-6">
            <div class="card">
                <h2>Delete Course</h2>
                <p>Are you sure you want to delete "{{ program_data.title }}"?</p>

                <form method="post" action="{% url 'vora:delete_course' program_data.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <a href="{% url 'vora:course_view' %}">Cancel</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/vora/pages/courses/edit_course.html
{% extends 'vora/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}

    <style>
        .ckeditor {
            width: 100% !important
        }
    </style>

{% endblock %}

{% block message %}
{% include 'vora/elements/alert.html' %}
{% endblock %}

{% block content %}
<form  method="post" enctype="multipart/form-data" novalidate autocomplete="off">
    {% csrf_token %}
    <div class="row items-align-center justify-content-center">
        <div class="col-xl-9 col-lg-9">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Edit Program</h4>
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        <form>

                            <div class="form-row">
                                <div class=" col-md-12">
                                    <div class="form-group">

                                        {{ form.media }}
                                        {{ form.as_p }}

                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                            <button type="submit" class="btn btn-primary">Update</button>
                        </form>
                </div>
            </div>
        </div>
    </div>	
 </form>
 
 
 
 {% endblock %}
 
 
 {% block additional_js %}
 
 
 
 
 <script>
    function readURL(input) {
 
       if (input.files && input.files[0]) {
             var reader = new FileReader();
             reader.onload = function(e) {
                $('#imagePreview').css('background-image', 'url('+e.target.result +')');
                $('#imagePreview').hide();
                $('#imagePreview').fadeIn(650);
             }
             reader.readAsDataURL(input.files[0]);
       }
    }
    $("#id_avatar").change(function() {
       readURL(this);
    });
 </script> 
 
 
 <script>
    $(".multi-select").select2({
       placeholder: "Select the Role"
   });
 </script>
 
 
 {% endblock %}